name: Manage GKE Cluster

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
          - plan
      cluster:
        description: "GKE cluster to manage (format: project/cluster-name)"
        required: true
        type: string
      environment:
        description: "Environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - perimeter
          - sandbox
          - production

permissions:
  contents: read
  id-token: write

jobs:
  manage-gke:
    name: ${{ inputs.action }} GKE Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup prerequisites
        uses: ./.github/actions/setup-prerequisites

      - name: Setup GCP authentication
        uses: ./.github/actions/setup-gcp-auth
        with:
          service-account-key: ${{ secrets.TF_SA_KEY }}

      - name: Parse cluster input
        id: parse
        run: |
          IFS='/' read -r PROJECT CLUSTER <<< "${{ inputs.cluster }}"
          echo "project=${PROJECT}" >> $GITHUB_OUTPUT
          echo "cluster=${CLUSTER}" >> $GITHUB_OUTPUT

      - name: Determine cluster path
        id: path
        run: |
          # Map environment to account structure
          case "${{ inputs.environment }}" in
            development)
              ACCOUNT="non-production"
              ENV_PATH="development"
              ;;
            perimeter)
              ACCOUNT="non-production"
              ENV_PATH="perimeter"
              ;;
            sandbox)
              ACCOUNT="non-production"
              ENV_PATH="sandbox"
              ;;
            production)
              ACCOUNT="prod-account"
              ENV_PATH="production"
              ;;
          esac

          # Find the cluster directory
          CLUSTER_PATH="live/${ACCOUNT}/${ENV_PATH}/${{ steps.parse.outputs.project }}/europe-west2/gke/${{ steps.parse.outputs.cluster }}"

          if [ ! -d "${CLUSTER_PATH}" ]; then
            echo "Error: Cluster path not found: ${CLUSTER_PATH}"
            exit 1
          fi

          echo "path=${CLUSTER_PATH}" >> $GITHUB_OUTPUT

      - name: Run terragrunt ${{ inputs.action }}
        run: |
          cd ${{ steps.path.outputs.path }}

          case "${{ inputs.action }}" in
            plan)
              terragrunt run plan --terragrunt-non-interactive
              ;;
            apply)
              terragrunt run apply --auto-approve --terragrunt-non-interactive
              ;;
            destroy)
              terragrunt run destroy --auto-approve --terragrunt-non-interactive
              ;;
          esac
